import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "65010362",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Navbar */}
        <nav className=" py-10">
          <div className="container mx-auto flex justify-between items-center font-von">
            <div className="text-white font-bold text-2xl">65010362</div>
            <ul className="flex space-x-4 font-semibold">
              <li>
                <a
                  href="/"
                  className="text-white text-2xl px-4  hover:text-kaki transition-all duration-300 ease-in-out"
                >
                  View config
                </a>
              </li>

              <li>
                <a
                  href="/temperature"
                  className="text-white text-2xl px-4  hover:text-kaki transition-all duration-300 ease-in-out"
                >
                  Temperature logs
                </a>
              </li>
              <li>
                <a
                  href="/viewlogs"
                  className="text-white text-2xl px-4  hover:text-kaki transition-all duration-300 ease-in-out"
                >
                  View logs
                </a>
              </li>
            </ul>
          </div>
        </nav>

        {/* Page Content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
